/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shnaider_Main */

#ifndef _Included_com_shnaider_Main
#define _Included_com_shnaider_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shnaider_Main
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_shnaider_Main_start
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
